openapi: 3.0.1
info:
  title: Flashcard API
  version: "0.1.0"
  description: API for managing flashcards
  contact:
    email: armando.braho02@gmail.com

servers:
  - url: http://localhost:8080/
paths:
  /flashcards:
    get:
      summary: Get all flashcards
      operationId: getAllFlashcards
      tags:
        - flashcards
      responses:
        200:
          description: A list of flashcards is returned
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'flashcard.yml#/components/schemas/FlashcardDto'
        # do I need an 500 in this case ????
    post:
      summary: Create a new flashcard
      operationId: createFlashcard
      tags:
        - flashcards
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'flashcard.yml#/components/schemas/FlashcardDto'
      responses:
        201:
          description: Flashcard created successfully
          content:
            application/json:
              schema:
                $ref: 'flashcard.yml#/components/schemas/FlashcardDto'
        400:
          description: Bad request
        500:
          description: Internal Server error

  /flashcards/{flashcardID}:
    get:
      summary: Get a  flashcard by ID(flashcardID)
      operationId: getFlashcard
      tags:
        - flashcards
      parameters:
        - name: flashcardID
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Found flashcard
          content:
            application/json:
              schema:
                $ref: 'flashcard.yml#/components/schemas/FlashcardDto'
        404:
          description: Flashcard not found
        500:
          description: Internal Server error
    put:
      summary: update the knowledgeLevel of a flashcard with a certain flashcardID
      operationId: updateLevelFlashcard
      tags:
        - flashcards
      parameters:
        - name: flashcardID
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'repetition-feedback.yml#/components/schemas/RepetitionFeedback'
      responses:
        200:
          description: Flashcard updated successfully
          content:
            application/json:
              schema:
                $ref: 'flashcard.yml#/components/schemas/FlashcardDto'
        400:
          description: Bad request
        500:
          description: Internal Server error

    delete:
      summary: Delete a flashcard by ID
      operationId: deleteFlashcard
      tags:
        - flashcards
      parameters:
        - name: flashcardID
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Flashcard deleted successfully
        400:
          description: Bad request

  /flashcards/expiredFlashcards:
    get:
      summary: Get all expired flashcards
      operationId: getExpiredFlashcards
      tags:
        - flashcards
      responses:
        200:
          description: A list of expired flashcards
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'flashcard.yml#/components/schemas/FlashcardDto'
        500:
          description: Internal Server error
                  # do I need to return the expirationDate?? The user itself atm does not see it and the FE asks the BE which cards should be repeated today. Maybe later
                  #for stats and customized settings of the user we may need to send such info to FE